services:
  DSCI522-2425-21-housing:
    image:  thamermsd/dsci522-2425-21-housing:374a034
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
