name: '522-group21-housing'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - vegafusion=1.6.9
  - vega_datasets=0.9.0
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - conda-lock=2.5.7
  - altair-all=5.4.*
  - pandas=2.2.3
  - ipykernel=6.29.5
  - nb_conda_kernels=2.5.1
  - click=8.1.7
  - quarto=1.5.57
  - nbformat=5.10.4
  - nbclient=0.10.1
  - pytest=8.3.4

# The following are included in python and don't need to be installed separately:
#  - os
#  - pickle

