name: '522-group21-housing'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - vegafusion=1.6.9
  - vega_datasets
  - scipy
  - scikit-learn
  - conda-lock
  - altair-all=5.4.*
  - pandas
  - ipykernel
  - nb_conda_kernels
#  - os
