name: '522-group21-housing'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pandas
  - ipykernel
  - nb_conda_kernels
  - altair-all=5.4.*
  - vegafusion=1.6.9
  - vega_datasets
  - scikit-learn
  - conda-lock
